### ISSUE TITLE
TypeError: validate_object_path() argument 1 must be str, not None

### ISSUE THREAD

**Issue by ywc-hb** [ukBaz/python-bluezero#257]
Hello ! 
I'm actually trying to send and receive values between my raspberry pi 4 and my micro:bit but when I've tried the python code of that tuto : https://ukbaz.github.io/howto/ubit_workshop.html to sending a message and display it on the microbit screen, I get this error, while my microbit is connected to my raspberry : 

```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    ubit.connect()
  File "/usr/local/lib/python3.7/dist-packages/bluezero/microbit.py", line 148, in connect
    self.ubit.connect()
  File "/usr/local/lib/python3.7/dist-packages/bluezero/central.py", line 84, in connect
    self.load_gatt()
  File "/usr/local/lib/python3.7/dist-packages/bluezero/central.py", line 60, in load_gatt
    chrc.resolve_gatt()
  File "/usr/local/lib/python3.7/dist-packages/bluezero/GATT.py", line 125, in resolve_gatt
    self.chrc_uuid)
  File "/usr/local/lib/python3.7/dist-packages/bluezero/dbus_tools.py", line 293, in get_methods
    return get_dbus_iface(iface, get_dbus_obj(path_obj))
  File "/usr/local/lib/python3.7/dist-packages/bluezero/dbus_tools.py", line 86, in get_dbus_obj
    return bus.get_object(constants.BLUEZ_SERVICE_NAME, dbus_path)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 244, in __init__
    _dbus_bindings.validate_object_path(object_path)
TypeError: validate_object_path() argument 1 must be str, not None
```

I've tried to remove my microbit from paired devices and pair it again, but it didn't work...

Thanks for your help !

**Comment by ukBaz** [comment]
Let us divide this problem up to see if it is an issue with Python or the Raspberry Pi/micro:bit.

My plan is to use `bluetoothctl` to establish that the Bluetooth communication is working OK between the micro:bit and the Raspberry Pi.

In the `bluetoothctl` window after you have done the pairing. Connect to the micro:bit. (I'll use `E3:AC:D2:F8:EB:B9` but you would use whatever is the address of your micro:bit)
```
[bluetooth]# connect E3:AC:D2:F8:EB:B9
```
Once it has successfully connected, open another terminal window on the RPi and type this command  (this is to find out where the information about the micro:bit button B is stored in the Bluetooth system):
```
gdbus introspect --system --dest org.bluez --object-path / --recurse | grep -i -B17 DA91 | grep node
```
You should get an answer that looks something like:
```
            node /org/bluez/hci0/dev_E3_AC_D2_F8_EB_B9/service002b/char002f {
```
We will now take this path information back into `bluetoothctl` so we can read it in there. So back in the first terminal window where `bluetoothctl` is running and connected to the micro:bit. We will select the attribute using the path we just found:
```
[BBC micro:bit [tuzep]]# select-attribute /org/bluez/hci0/dev_E3_AC_D2_F8_EB_B9/service002b/char002f
```
Now reading the attribute it should return zero:
```
[BBC micro:bit [tuzep]:/service002b/char002f]# read
Attempting to read /org/bluez/hci0/dev_E3_AC_D2_F8_EB_B9/service002b/char002f
[CHG] Attribute /org/bluez/hci0/dev_E3_AC_D2_F8_EB_B9/service002b/char002f Value: 0x00
  00
```
If you press and hold the Button B on the micro:bit down and at the same time do a read you will get a non-zero value (1 = short press & 2 = long press)
```                                               .
[BBC micro:bit [tuzep]:/service002b/char002f]# read
Attempting to read /org/bluez/hci0/dev_E3_AC_D2_F8_EB_B9/service002b/char002f
[CHG] Attribute /org/bluez/hci0/dev_E3_AC_D2_F8_EB_B9/service002b/char002f Value: 0x02
  02       
```

If this works then, then things are setup correctly and we can focus on the Python. If there are issues with the above then we need to focus on that.

**Comment by ln-komandur** [comment]
Thanks @ukBaz, 
I get the same error as @ywc-hb  when executing the "Sending a message to the micro:bit" python example code in https://ukbaz.github.io/howto/ubit_workshop.html 

> $ python3 microbit-example1.py 
Traceback (most recent call last):
  File "microbit-example1.py", line 11, in <module>
    ubit.connect()
  File "/usr/local/lib/python3.7/dist-packages/bluezero/microbit.py", line 148, in connect
    self.ubit.connect()
  File "/usr/local/lib/python3.7/dist-packages/bluezero/central.py", line 84, in connect
    self.load_gatt()
  File "/usr/local/lib/python3.7/dist-packages/bluezero/central.py", line 60, in load_gatt
    chrc.resolve_gatt()
  File "/usr/local/lib/python3.7/dist-packages/bluezero/GATT.py", line 125, in resolve_gatt
    self.chrc_uuid)
  File "/usr/local/lib/python3.7/dist-packages/bluezero/dbus_tools.py", line 293, in get_methods
    return get_dbus_iface(iface, get_dbus_obj(path_obj))
  File "/usr/local/lib/python3.7/dist-packages/bluezero/dbus_tools.py", line 86, in get_dbus_obj
    return bus.get_object(constants.BLUEZ_SERVICE_NAME, dbus_path)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 244, in __init__
    _dbus_bindings.validate_object_path(object_path)
TypeError: validate_object_path() argument 1 must be str, not None
$


I followed steps similar to the approach you have suggested to separate the problem between `bluetoothctl` and `python3` . I am able to successfully read Button B as below after scanning and connecting microbit from my raspberry pi using `bluetoothctl` . But I am stuck on the python3 part.

> [BBC micro:bit [tuzut]]# menu gatt
[BBC micro:bit [tuzut]]# list-attributes
........
........
Characteristic
	/org/bluez/hci0/dev_CC_4F_26_07_68_A8/service002b/char002f
	e95dda91-251d-470a-a062-fa1922dfa9a8
	MicroBit Button B State
Descriptor
	/org/bluez/hci0/dev_CC_4F_26_07_68_A8/service002b/char002f/desc0031
	00002902-0000-1000-8000-00805f9b34fb
	Client Characteristic Configuration
........
........
[BBC micro:bit [tuzut]]# select-attribute /org/bluez/hci0/dev_CC_4F_26_07_68_A8/service002b/char002f
[BBC micro:bit [tuzut]:/service002b/char002f]#
[BBC micro:bit [tuzut]:/service002b/char002f]# read
Attempting to read /org/bluez/hci0/dev_CC_4F_26_07_68_A8/service002b/char002f
[CHG] Attribute /org/bluez/hci0/dev_CC_4F_26_07_68_A8/service002b/char002f Value:
  00                                               .               
  00 
[BBC micro:bit [tuzut]:/service002b/char002f]# read
Attempting to read /org/bluez/hci0/dev_CC_4F_26_07_68_A8/service002b/char002f
[CHG] Attribute /org/bluez/hci0/dev_CC_4F_26_07_68_A8/service002b/char002f Value:
  01                                               .               
  01                                               .               
[BBC micro:bit [tuzut]:/service002b/char002f]# read
Attempting to read /org/bluez/hci0/dev_CC_4F_26_07_68_A8/service002b/char002f
[CHG] Attribute /org/bluez/hci0/dev_CC_4F_26_07_68_A8/service002b/char002f Value:
  02                                               .               
  02                                               .               
[BBC micro:bit [tuzut]:/service002b/char002f]# 

Here are some details on the installations and versions on my Raspberry Pi 3B

> $ uname -a
Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
$ python3 --version
Python 3.7.3
$ bluetoothctl --version
bluetoothctl: 5.50


I am new to Python. Would appreciate any directions on troubleshooting the python part. Thanks.

**Comment by ukBaz** [comment]
I copied the code from from the workshop link and modified the addresses for the adapter and the device.
I created a Pythyon Virtual Environment and installed bluezero with pip.
I created the micro:bit code using the latest MakeCode editor and loaded it on the micro:bit. I had problems pairing (have others seen this?) so I put the micro:bit 'no pairing required mode'
I've also run it in a separate area on disk to make sure I'm not picking up my development code.
Transcript of run:
```
(venv) pi@raspberrypi:~/stack_overflow $ python bluez_workshop.py 
Enter message: Test
Enter message: Long words
Enter message: 
```
This worked at expected.

I checked the versions and they seemed to match with what you reported.
```
(venv) pi@raspberrypi:~/stack_overflow $ uname -a
Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
(venv) pi@raspberrypi:~/stack_overflow $ python3 --version
Python 3.7.3
(venv) pi@raspberrypi:~/stack_overflow $ bluetoothctl --version
bluetoothctl: 5.50
```

This makes it difficult for me to debug as it works for me. 

@ln-komandur, I noticed in your bluetoothctl log that you interacted with the button Characteristic, while the code will use the led text characteristic.

My suspicion is that there is either an issue with the code you have entered. Or more likely, that the micro:bit Bluetooth services started and the Bluetooth services in your code don't match. Or possibly some dependency missing on you system.
It is now how we prove or rule those out.

Can you confirm your micro:bit has the same services as the one I have:
```
(venv) pi@raspberrypi:~/stack_overflow $ bluetoothctl info DC:DB:16:6B:8C:5F
Device DC:DB:16:6B:8C:5F (random)
        Name: BBC micro:bit [zegig]
        Alias: BBC micro:bit [zegig]
        Appearance: 0x0200
        Paired: no
        Trusted: no
        Blocked: no
        Connected: no
        LegacyPairing: no
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
        UUID: MicroBit Accelerometer... (e95d0753-251d-470a-a062-fa1922dfa9a8)
        UUID: MicroBit Temperature Se.. (e95d6100-251d-470a-a062-fa1922dfa9a8)
        UUID: MicroBit Event Service    (e95d93af-251d-470a-a062-fa1922dfa9a8)
        UUID: MicroBit DFU Control Se.. (e95d93b0-251d-470a-a062-fa1922dfa9a8)
        UUID: MicroBit Button Service   (e95d9882-251d-470a-a062-fa1922dfa9a8)
        UUID: MicroBit LED Service      (e95dd91d-251d-470a-a062-fa1922dfa9a8)
        UUID: Vendor specific           (e97dd91d-251d-470a-a062-fa1922dfa9a8)
        AdvertisingFlags:
  06                                               .               
```
And that the micro:bit instantiation is the same:
```python
from bluezero import microbit
ubit = microbit.Microbit(adapter_addr='B8:27:EB:22:57:E0',
                         device_addr='DC:DB:16:6B:8C:5F',
                         accelerometer_service=True,
                         button_service=True,
                         led_service=True,
                         magnetometer_service=False,
                         pin_service=False,
                         temperature_service=True)
my_text = 'Hello, world'
ubit.connect()

while my_text is not '':
    ubit.text = my_text
    my_text = input('Enter message: ')

ubit.disconnect()
```
