### ISSUE TITLE
Not working in venv

### ISSUE THREAD

**Issue by ukBaz** [ukBaz/python-bluezero#317]
Doesn't seem to work without this. Is there another way to get it working?

On Raspberry Pi running `python script.py` from venv doesn't work. I'm running as `pi` user and I've added `pi` user to `bluetooth` group.

_Originally posted by @MaikuMori in https://github.com/ukBaz/python-bluezero/issues/315#issuecomment-770622944_

**Comment by MaikuMori** [comment]
Thanks, for opening this. I didn't want to open an issue in case it was something simple.

**Comment by ukBaz** [comment]
I think this might be a different issue. There is a dependency in Bluezero on using Python D-Bus which on the RPi is in the main system python install. I have typically solved this by using the option `--system-site-packages`. Although the down side of that is that you lose much of the benefit of having a venv.

You might want to have a look at pip installing https://pypi.org/project/dbus-python/ in your venv as that might get you around the issue. You might also need https://pypi.org/project/vext.gi/

**Comment by MaikuMori** [comment]
I believe I have it already installed.

These are my dependencies:
```toml
[tool.poetry.dependencies]
python = "^3.9"
bluezero = "^0.5.0"
dbus-python = "^1.2.16"
PyGObject = "^3.38.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.4"
black = {version = "^20.8b1", allow-prereleases = true}
```

With a modified version of the old dbus config most stuff works. I have a peripheral which I can connect and interact with my phone. I'm currently having some trouble with central, but I don't think it's related. If I remove the dbus config nothing works.
